# Generated by Django 2.0.12 on 2020-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20200304_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'exav'), ('accepted', 'gnac'), ('delivered', 'beruma')], max_length=15, null=True, verbose_name='status'),
        ),
    ]
