# Generated by Django 2.0.12 on 2020-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20200307_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('delivered', 'delivered')], max_length=15, null=True, verbose_name='status'),
        ),
    ]
